### ISSUE TITLE
Crash when rain cutter sword hits iron's spell n spellbook summoned entities

### ISSUE THREAD

**Issue by Riyuukii** [SettingDust/dawncraft-fixes#12]
DawnCraft version: 2.0.12

How to reproduce:
1. Spawn any iron's spell and spellbook summoned entities.
2. Use the rain cutter identity skill and make the raincutter sword to hit the summoned entities.

**Comment by SettingDust** [comment]
Wrong repo to report. Reposted in the correct repo

**Comment by Riyuukii** [comment]
> Wrong repo to report. Reposted in the correct repo

Thank you!
