### ISSUE TITLE
Cloud Storage Search not working

### ISSUE THREAD

**Issue by PierKnight** [SettingDust/dawncraft-fixes#3]
The search bar doesn't order the cloud storage inventory, the thing is that It does work in a modpack with only the cloud storage mod, the mod and minecraft version are the same .

Here is two screenshots https://imgur.com/a/1TzWbCa

And I think this might be the culprit https://pastebin.com/FGeiv1rF

**Comment by PierKnight** [comment]
I've tested Epic Fight and Cloud Storage together and I can confirm that It doesn't work,
It seems EpicFight tries to cast his capability inside his ItemTooltipEvent to a LocalPlayerPatch, so I assume the mod expects that the event is called only on client side, but If I recall correctly that event can be called on server just like how the cloud storage does

**Comment by PierKnight** [comment]
I've got some time and created a pull request with a first approach that fixes the problem #4

**Comment by SettingDust** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/mod-compat-fixes/files/4558394

**Comment by Yesssssman** [comment]
```
if (event.getPlayer() != null && event.getPlayer().level.isClientSide) {
```

I inserted this code on efm so you don't have to use the mixin anymore
I never expected someone who'd use this method on the server side :joy:

Btw it'll take some time before the next update is released.

**Comment by SettingDust** [comment]
> ```
> if (event.getPlayer() != null && event.getPlayer().level.isClientSide) {
> ```
> 
> I inserted this code on efm so you don't have to use the mixin anymore I never expected someone who'd use this method on the server side 😂

Ya. I've wrapped the cloud storage search with try catch with mixin. So, it's won't an issue XD. Cloud Storage searching breaking so many mods
