### ISSUE TITLE
java.lang.NullPointerException: Cannot assign field "f_19802_" because "trueEntity" is null

### ISSUE THREAD

**Issue by DeshiDesu** [SettingDust/dawncraft-fixes#6]
EpicFight-18.3.8.jar
irons_spellbooks-1.18.2-1.1.4.1.jar
dawncraft-fixes-0.10.1.jar

Tested on Forge 40.1.80 and 40.2.9

Tried the latest update to fix this issue but the error persists. Any ideas?

[crash-2023-06-15_20.52.33-server.txt](https://github.com/SettingDust/dawncraft-fixes/files/11764338/crash-2023-06-15_20.52.33-server.txt)

**Comment by SettingDust** [comment]
Ya. I'm trying to fix this issue. But seems not cover all situation
Is it appears when you died?

**Comment by SettingDust** [comment]
It's another issue. Not realting to the one I try to fix

**Comment by SettingDust** [comment]
That's should not happen. How can you reproduce it?

**Comment by DeshiDesu** [comment]
Hit any mob from Iron's spells n' spellbooks or die from them. I'm not sure which of these conditions triggers this crash and if it only happens to mobs from this mod. I will do some more testing to find out.

**Comment by SettingDust** [comment]
reproduce with jar in this zip and find the log line before the crash 
[dawncraft-fixes-0.11.0.zip](https://github.com/SettingDust/dawncraft-fixes/files/11770320/dawncraft-fixes-0.11.0.zip)

**Comment by DeshiDesu** [comment]
I tried reproducing again with the jar and got this:
>com.llamalad7.mixinextras.injector.wrapoperation.IncorrectArgumentCountException: Incorrect number of arguments passed to Operation::call! Expected 1 but got 0. Expected types were [java.lang.Object], actual types were [].
[crash-2023-06-16_09.20.14-server.txt](https://github.com/SettingDust/dawncraft-fixes/files/11770661/crash-2023-06-16_09.20.14-server.txt)

**Comment by SettingDust** [comment]
I'll debug in local

**Comment by SettingDust** [comment]
can't reproduce after kill

**Comment by SettingDust** [comment]
[dawncraft-fixes-0.11.0.zip](https://github.com/SettingDust/dawncraft-fixes/files/11778553/dawncraft-fixes-0.11.0.zip)

**Comment by DeshiDesu** [comment]
Ill try again because that was on my laptop

**Comment by DeshiDesu** [comment]
Im guessing the crash occurs when you attack and die at the same time?
https://github.com/SettingDust/dawncraft-fixes/assets/120287925/65dc8c15-08c3-4839-b0b8-4cebe0660e13

Mods:
caelus-forge-1.18.1-3.0.0.2
curios-forge-1.18.2-5.0.9.0
dawncraft-fixes-0.11.0
EpicFight-18.3.7
geckolib-forge-1.18-3.0.57
irons_spellbooks-1.18.2-1.1.4.1
player-animation-lib-forge-1.0.2+1.18

[crash-2023-06-17_10.51.01-server.txt](https://github.com/SettingDust/dawncraft-fixes/files/11779294/crash-2023-06-17_10.51.01-server.txt)

**Comment by DeshiDesu** [comment]
Don't mind the background sound, that was youtube 😅


https://github.com/SettingDust/dawncraft-fixes/assets/120287925/8c962ae5-7953-4779-a878-e68574063c62


[crash-2023-06-17_11.03.28-server.txt](https://github.com/SettingDust/dawncraft-fixes/files/11779317/crash-2023-06-17_11.03.28-server.txt)

**Comment by DeshiDesu** [comment]
@SettingDust thank you so much 😊😊😊
