### ISSUE TITLE
Crash at startup when Goblins & Dungeons is installed

### ISSUE THREAD

**Issue by DeshiDesu** [SettingDust/dawncraft-fixes#7]
Installed Mods:
dawncraft-fixes-0.10.1.jar
Goblins_Dungeons_1.0.8.jar
Forge 40.2.9

Error:
> java.lang.NullPointerException: Cannot read field "f_46443_" because "p_77624_2_" is null

[crash-2023-06-16_17.49.20-client.txt](https://github.com/SettingDust/dawncraft-fixes/files/11776264/crash-2023-06-16_17.49.20-client.txt)

**Comment by SettingDust** [comment]
fixed in dev. haven't published. Will publish after fix #6
